config/routes.rb
GamingApp::Application.routes.draw do
  root "games#index"

  resources :secret_numbers, :only => [:new, :show]
  resources :rock_paper_scissors, :only => [:new, :show]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end
end

app/controllers/rock_paper_scissors_controller.rb
class RockPaperScissorsController < ApplicationController
  def new
    @throws = get_throws
  end

  def show
    @throws = get_throws
    # use a random number to set a random throw for the Game
    @game_throw = @throws[rand(3)]
    # use the params[:id] again to set the user's throw
    @user_throw = @throws[params[:id].to_i]
    # calculate the result of the game based on the throws
    @result = game_result(@game_throw, @user_throw)
  end

  private

    def get_throws
      [:rock, :paper, :scissors]
    end

    def game_result(game_throw, user_throw)
      # create a hash which maps each throw (key)
      # to the throw that it beats (value)
      # e.g. beats["rock"] => "scissors" implies rock beats scissors
      beats = {
        rock: :scissors,
        scissors: :paper,
        paper: :rock
      }

      # beats[@user_throw] is the throw the user can beat
      if beats[@user_throw] == @game_throw
        # if the game's throw is the one that the
        # user's throw beats, they win!
        @status = :win
      elsif user_throw == @game_throw
        # if both throws are the same, it's a tie
        @status = :tie
      else
        # otherwise, the user loses
        @status = :loss
      end
    end
end

app/controllers/secret_numbers_controller.rb
class SecretNumbersController < ApplicationController
  def new
  end

  def show
    # get a random number from 1-10
    @secret_number = rand(5)+1

    # get the user chosen number from params
    # the param is named 'id' because of route convention
    # lastly, we want to turn it from a String to an Integer
    # that way, we can compare it to the secret number (which is an int)
    @chosen_number = params[:id].to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
  def game_state(count, singular_state)
    if count == 1
      singular_state
    else
      'are'
    end
  end
end

app/views/games/index.html.erb
<h1>Welcome to the Game Center!</h1>

<p>Choose a game below to get started:</p>

<br/>

<table>
  <tr>
    <td>
      <%=link_to image_tag("games/secret-number.jpg"), new_secret_number_path %>
      <h4>SECRET NUMBER</h4>
    </td>
    <td>
      <%=link_to image_tag("games/rock-paper-scissors.jpg"), new_rock_paper_scissor_path %>
      <h4>ROCK PAPER SCISSORS</h4>
    </td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Games on Rails</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!-- Built with love by Salman Ansari, BEWD Instructor in Sep 2013 -->
</head>
<body>

<% unless controller.controller_name == 'games' %>
  <%= link_to '< Back to Game Center', '/' %>
<% end %>

<div id="content">
  <%= yield %>
</div>

</body>
</html>

app/views/rock_paper_scissors/new.html.erb
<h1>Welcome to Rock Paper Scissors!</h1>

</br>

<h4>To play the game, choose a throw:</h4>

<table>
  <tr>
    <% @throws.each_with_index do |throw, num| %>
      <td>
        <%=link_to image_tag("rock_paper_scissors/#{throw}.jpeg"), rock_paper_scissor_path(num) %>
        <h3><%=throw.upcase%></h3>
      </td>
    <% end %>
  </tr>
</table>

app/views/rock_paper_scissors/show.html.erb
<table>
  <tr>
    <td>
      <p>You threw:</p>
      <%=image_tag "rock_paper_scissors/#{@user_throw}.jpeg" %>
      <h4><%=@user_throw.upcase%></h4>
    </td>
    <td>
      <h1>VS.</h1>
    </td>
    <td>
      <p>Rails threw:</p>
      <%=image_tag "rock_paper_scissors/#{@game_throw}.jpeg" %>
      <h4><%=@game_throw.upcase%></h4>
    </td>
  </tr>
</table>

<% if @status == :win %>
  <h1>CONGRATS! YOU WIN!</h1>
  <%= image_tag "games/winner.gif" %>
<% elsif @status == :tie %>
  <h1>It's a tie!</h2>
  <%= image_tag "games/tie.jpg" %>
<% else %>
  <h1>Sorry, you lose...</h1>
  <%= image_tag "games/cat-always-wins.jpeg" %>
<% end %>

<br/>

<h2><%=link_to "PLAY AGAIN", new_rock_paper_scissor_path %></h2>

app/views/secret_numbers/new.html.erb
<h1>Welcome to Secret Number!</h1>

<p>To play this game, all you have to do is guess a number. If you guess the <u>secret number</u>, you win!</p>

<p>Choose carefully... you only get one try!</p>

<br/>

<h2>Pick a number:<h2>

<% (1..5).each do |number| %>
  <%= link_to image_tag("secret_numbers/#{number}.jpeg"), secret_number_path(number) %>
<% end %>

app/views/secret_numbers/show.html.erb
<% if @secret_number == @chosen_number %>
  <h1>CONGRATS! YOU WON!</h1>
  <h4>The secret number was <%=@secret_number%></h4>
  <p><%= image_tag 'games/cat-wins.gif' %></p>
<% else %>
  <h1>Sorry, you lose...</h1>
  <h4>The secret number was <%=@secret_number%></h4>
  <p><%= image_tag 'games/loser.gif' %></p>
<% end %>

<p>
  <h3><%= link_to "PLAY AGAIN", new_secret_number_path %></h3>
</p>